// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBpW6sFyJt5hIhFyZAC6rdMJ5TMSHhEGjk',
    appId: '1:881519180730:web:16b1253b30b4d7cf28fb83',
    messagingSenderId: '881519180730',
    projectId: 'timeee-e88d8',
    authDomain: 'timeee-e88d8.firebaseapp.com',
    storageBucket: 'timeee-e88d8.appspot.com',
    measurementId: 'G-DJKJJ0R5Y9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDkNs_IbBUIdMAntnUfrEjloxpsvwcZkzI',
    appId: '1:881519180730:android:9e3c2fc9f8f0847828fb83',
    messagingSenderId: '881519180730',
    projectId: 'timeee-e88d8',
    storageBucket: 'timeee-e88d8.appspot.com',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBpW6sFyJt5hIhFyZAC6rdMJ5TMSHhEGjk',
    appId: '1:881519180730:web:ad713ce084f06f1528fb83',
    messagingSenderId: '881519180730',
    projectId: 'timeee-e88d8',
    authDomain: 'timeee-e88d8.firebaseapp.com',
    storageBucket: 'timeee-e88d8.appspot.com',
    measurementId: 'G-27YLT1J5Q3',
  );
}
